const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
const firstElement = languages[0];
const thirdElement = languages[2];
const length = languages.length;
const lastElement = languages.length - 1;
console.log(languages);
console.log(firstElement);
console.log(thirdElement);
console.log(length);
console.log(lastElement);
