const number1 = 3;
const number2 = 7;
const product = number1 * number2;
const charge = 12;
const payment = 4;
const amountRemaining = charge - payment;
const tests = 70;
const assignments = 90;
const final = 85;
const grade = (tests + assignments + final) / 3;
const firstName = 'Alex';
const lastName = 'Ehrenkranz';
const fullName = `${firstName} ${lastName}`;
const pH = 7;
const isAcidic = pH < 7;
const numberOfSoldiers = 777;
const isSparta = numberOfSoldiers === 300;
let nickname = fullName;
nickname += ' is the GOAT';
console.log(product);
console.log(typeof product);
console.log(amountRemaining);
console.log(typeof amountRemaining);
console.log(grade);
console.log(typeof grade);
console.log(fullName);
console.log(typeof fullName);
console.log(isAcidic);
console.log(typeof isAcidic);
console.log(isSparta);
console.log(typeof isSparta);
console.log(nickname);
console.log(typeof nickname);
